source "https://rubygems.org"

ruby "3.4.5"

gem "nats-pure", "~> 2.0"
gem "httparty", "~> 0.21"
gem "json", "~> 2.6"
gem "yaml", "~> 0.2"
gem "activesupport", "~> 8.0"
gem "tzinfo", "~> 2.0"

group :development, :test do
  gem "rspec", "~> 3.12"
  gem "faker", "~> 3.2"
end
