source "https://rubygems.org"

ruby "3.4.5"

gem "rails", "~> 8.0.2"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "propshaft"
gem "jbuilder"
gem "redis", "~> 4.0"
gem "bootsnap", require: false
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "solid_cable"
gem "solid_cache"
gem "solid_queue"

gem "nats-pure", "~> 2.0"
gem "tailwindcss-rails", "~> 2.0"
gem "httparty", "~> 0.21"
gem "json", "~> 2.6"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails"
  gem "cucumber-rails", require: false
  gem "database_cleaner"
  gem "factory_bot_rails"
  gem "faker"
  gem "simplecov", require: false
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara", "~> 3.40"
  gem "selenium-webdriver", "~> 4.10"
  gem "webdrivers", "~> 5.3"
end

